// Generated by Selenium IDE
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.testng.annotations.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;
import java.time.Duration;

public class JavaAPITest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    Duration duration = Duration.ofMillis(500);

    @Before
    public void setUp() {
        //driver = new FirefoxDriver();
        System.setProperty("webdriver.chrome.driver","C:/Users/cjdra/Documents/Penn State/SWENG 431/Lab10/src/main/resources/chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void javaAPI() {
        setUp();
        driver.get("https://docs.oracle.com/javase/9/docs/api/overview-summary.html");
        driver.manage().window().setSize(new Dimension(1076, 693));
        driver.manage().timeouts().implicitlyWait(duration);
        driver.findElement(By.linkText("Java SE")).click();
        driver.findElement(By.id("search")).click();
        driver.findElement(By.id("search")).sendKeys("java.lang.String");
        driver.findElement(By.id("search")).sendKeys(Keys.ENTER);
        driver.findElement(By.cssSelector(".rowColor:nth-child(3) > .colConstructorName a")).click();
        driver.findElement(By.id("search")).click();
        driver.findElement(By.id("search")).sendKeys("javax.swing.jframe");
        driver.findElement(By.id("search")).sendKeys(Keys.DOWN);
        driver.findElement(By.id("search")).sendKeys(Keys.ENTER);
        driver.findElement(By.cssSelector(".altColor:nth-child(4) > .colConstructorName .memberNameLink > a")).click();
    }
}
